/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_smartdevice_test
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
	QakContext.createContexts(
	        "localhost", this, "sprint0_system_overview.pl", "sysRules.pl","ctx_smartdevice_test"
	)
}

