/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
class Transporttrolley ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 
				var stato: String = ""
			   	var pending: Boolean = false   	
				return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | init e engage basicrobot")
						request("engage", "engage(transporttrolley,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="engaged",cond=whenReply("engagedone"))
					transition(edgeName="t04",targetState="quit",cond=whenReply("engagerefused"))
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | basicrobot engaged")
						 stato = "inHome"  
						updateResourceRep( "azione(HOME)"  
						)
						updateResourceRep( "stato($stato)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | idle")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="moveToIndoor",cond=whenRequest("gotoindoor"))
					transition(edgeName="t06",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("moveToIndoor") { //this:State
					action { //it:State
						 stato = "toIndoor"  
						if(  (pending)  
						 ){ pending = false  
						}
						updateResourceRep( "azione(MOVING)"  
						)
						updateResourceRep( "stato($stato)"  
						)
						CommUtils.outmagenta("$name | vado all'INDOOR")
						request("moverobot", "moverobot(0,4)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="loadTheCharge",cond=whenReply("moverobotdone"))
					transition(edgeName="t08",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("loadTheCharge") { //this:State
					action { //it:State
						 stato = "inIndoor"  
						updateResourceRep( "azione(STOPPED)"  
						)
						updateResourceRep( "stato($stato)"  
						)
						CommUtils.outmagenta("$name | sono in INDOOR")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_loadTheCharge", 
				 	 					  scope, context!!, "local_tout_transporttrolley_loadTheCharge", 3000.toLong() )
					}	 	 
					 transition(edgeName="t9",targetState="loadDone",cond=whenTimeout("local_tout_transporttrolley_loadTheCharge"))   
					transition(edgeName="t10",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("loadDone") { //this:State
					action { //it:State
						answer("gotoindoor", "chargetaken", "chargetaken(_)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="moveToColdroom", cond=doswitch() )
				}	 
				state("moveToColdroom") { //this:State
					action { //it:State
						 stato = "toColdroom"  
						CommUtils.outmagenta("$name | vado verso la cold room")
						updateResourceRep( "azione(MOVING)"  
						)
						updateResourceRep( "stato($stato)"  
						)
						request("moverobot", "moverobot(4,3)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="storeTheCharge",cond=whenReply("moverobotdone"))
					transition(edgeName="t012",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("storeTheCharge") { //this:State
					action { //it:State
						 stato = "inColdroom"  
						updateResourceRep( "azione(STOPPED)"  
						)
						updateResourceRep( "stato($stato)"  
						)
						CommUtils.outmagenta("$name | sono in Cold Room")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_storeTheCharge", 
				 	 					  scope, context!!, "local_tout_transporttrolley_storeTheCharge", 3000.toLong() )
					}	 	 
					 transition(edgeName="t013",targetState="chargeDeposited",cond=whenTimeout("local_tout_transporttrolley_storeTheCharge"))   
					transition(edgeName="t014",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("chargeDeposited") { //this:State
					action { //it:State
						 stato = "deposited"  
						CommUtils.outmagenta("$name | terminato deposito. Aspetto istruzioni")
						updateResourceRep( "deposited"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="moveToIndoor",cond=whenRequest("gotoindoor"))
					transition(edgeName="t016",targetState="moveToHome",cond=whenDispatch("gohome"))
				}	 
				state("moveToHome") { //this:State
					action { //it:State
						 stato = "toHome"  
						updateResourceRep( "azione(MOVING)"  
						)
						updateResourceRep( "stato($stato)"  
						)
						CommUtils.outmagenta("$name | vado alla posizione HOME")
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="requestDuringHome",cond=whenRequest("gotoindoor"))
					transition(edgeName="t018",targetState="trolleyathome",cond=whenReply("moverobotdone"))
					transition(edgeName="t019",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("trolleyathome") { //this:State
					action { //it:State
						 stato = "inHome"  
						updateResourceRep( "azione(HOME)"  
						)
						updateResourceRep( "stato($stato)"  
						)
						CommUtils.outmagenta("$name | trolley at HOME")
						forward("setdirection", "dir(down)" ,"basicrobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="moveToIndoor", cond=doswitchGuarded({ pending  
					}) )
					transition( edgeName="goto",targetState="idle", cond=doswitchGuarded({! ( pending  
					) }) )
				}	 
				state("sonarobstacle") { //this:State
					action { //it:State
						discardMessages = true
						CommUtils.outmagenta("$name | Sono fermo per ostacolo sonar")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t020",targetState="requestDuringAlarm",cond=whenRequest("gotoindoor"))
					transition(edgeName="t021",targetState="idle",cond=whenEventGuarded("resume",{ stato == "inHome"  
					}))
					transition(edgeName="t022",targetState="moveToIndoor",cond=whenEventGuarded("resume",{ stato == "toIndoor"  
					}))
					transition(edgeName="t023",targetState="loadTheCharge",cond=whenEventGuarded("resume",{ stato == "inIndoor"  
					}))
					transition(edgeName="t024",targetState="moveToColdroom",cond=whenEventGuarded("resume",{ stato == "toColdroom"  
					}))
					transition(edgeName="t025",targetState="storeTheCharge",cond=whenEventGuarded("resume",{ stato == "inColdroom"  
					}))
					transition(edgeName="t026",targetState="chargeDeposited",cond=whenEventGuarded("resume",{ stato == "deposited"  
					}))
					transition(edgeName="t027",targetState="moveToHome",cond=whenEventGuarded("resume",{ stato == "toHome"  
					}))
				}	 
				state("requestDuringAlarm") { //this:State
					action { //it:State
						 stato = "toIndoor"  
						updateResourceRep( "stato($stato)"  
						)
						CommUtils.outmagenta("$name | trolley deve andare alla INDOOR quando l'alarm è terminato")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="sonarobstacle", cond=doswitch() )
				}	 
				state("requestDuringHome") { //this:State
					action { //it:State
						 
									stato = "toHome"
									pending = true
						updateResourceRep( "stato($stato)"  
						)
						CommUtils.outmagenta("$name | trolley deve andare alla INDOOR una volta a casa")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t28",targetState="trolleyathome",cond=whenReply("moverobotdone"))
					transition(edgeName="t29",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("quit") { //this:State
					action { //it:State
						forward("disengage", "disengage(transporttrolley)" ,"basicrobot" ) 
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
