/* Generated by AN DISI Unibo */ 
package it.unibo.serviceaccessgui

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Serviceaccessgui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var currentWeight: Float = 0.0f	
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outcyan("[ServiceAccessGui] Init")
						 currentWeight = 0.0f  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitevents", cond=doswitch() )
				}	 
				state("waitevents") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleGuicmd",cond=whenEvent("accessguicmd"))
					transition(edgeName="t01",targetState="handle_update_data",cond=whenDispatch("coldroomdata"))
					transition(edgeName="t02",targetState="handle_charge_taken",cond=whenDispatch("chargetaken"))
				}	 
				state("handleGuicmd") { //this:State
					action { //it:State
						discardMessages = false
						if( checkMsgContent( Term.createTerm("accessguicmd(CMD,ARG)"), Term.createTerm("accessguicmd(store,FW)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outcyan("[ServiceAccessGui] Sending store request")
								request("storerequest", "storerequest(${payloadArg(1)})" ,"coldstorageservice" )  
						}
						if( checkMsgContent( Term.createTerm("accessguicmd(CMD,ARG)"), Term.createTerm("accessguicmd(ticket,TICKET)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outcyan("[ServiceAccessGui] Sending ticket ")
								request("insertticket", "insertticket(${payloadArg(1)})" ,"coldstorageservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t13",targetState="handle_store_accepted",cond=whenReply("storeaccepted"))
					transition(edgeName="t14",targetState="handle_store_rejected",cond=whenReply("storerejected"))
					transition(edgeName="t15",targetState="handle_ticket_accepted",cond=whenReply("ticketaccepted"))
					transition(edgeName="t16",targetState="handle_ticket_rejected",cond=whenReply("ticketrejected"))
				}	 
				state("handle_update_data") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("coldroomdata(WEIGHT)"), Term.createTerm("coldroomdata(WEIGHT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												currentWeight = payloadArg(0).toFloat()	
								CommUtils.outcyan("[ServiceAccessGui] Updating weight -> $currentWeight ")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitevents", cond=doswitch() )
				}	 
				state("handle_store_accepted") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("storeaccepted(TICKET)"), Term.createTerm("storeaccepted(TICKET)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val TIMESTAMP = payloadArg(0)  
								CommUtils.outcyan("[ServiceAccessGui] Store Accepted. Received ticket $TIMESTAMP")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitevents", cond=doswitch() )
				}	 
				state("handle_store_rejected") { //this:State
					action { //it:State
						CommUtils.outcyan("[ServiceAccessGui] Store Rejected")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitevents", cond=doswitch() )
				}	 
				state("handle_ticket_accepted") { //this:State
					action { //it:State
						CommUtils.outcyan("[ServiceAccessGui] Ticket Accepted")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitevents", cond=doswitch() )
				}	 
				state("handle_ticket_rejected") { //this:State
					action { //it:State
						CommUtils.outcyan("[ServiceAccessGui] Ticket Rejected")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitevents", cond=doswitch() )
				}	 
				state("handle_charge_taken") { //this:State
					action { //it:State
						CommUtils.outcyan("[ServiceAccessGui] Charge Taken")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitevents", cond=doswitch() )
				}	 
			}
		}
}
