/* Generated by AN DISI Unibo */ 
package it.unibo.statusgui_proxy

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Statusgui_proxy ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 																
				val server = unibo.basicomm23.ws.WsConnection.create("localhost:8087/statusguiproxy")
				
				var currentRequest = "" 
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CoapObserverSupport(myself, "127.0.0.1","8020","ctxbasicrobot","basicrobot")
						CoapObserverSupport(myself, "127.0.0.1","8020","ctxbasicrobot","engager")
						CoapObserverSupport(myself, "127.0.0.1","8020","ctxbasicrobot","robotpos")
						CoapObserverSupport(myself, "127.0.0.1","8020","ctxbasicrobot","planexec")
						CoapObserverSupport(myself, "localhost","11802","ctx_coldstorage","coldstorageservice")
						CoapObserverSupport(myself, "localhost","11802","ctx_coldstorage","transporttrolley")
						CommUtils.outcyan("$name | init")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="observing", cond=doswitch() )
				}	 
				state("observing") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t0",targetState="handle_update",cond=whenDispatch("coapUpdate"))
				}	 
				state("handle_update") { //this:State
					action { //it:State
						if(  (currentMsg.msgContent().contains("robotpos"))  
						 ){
									    val coordinates = Regex("""RobotPos=\((\d+),(\d+)\)""").
									    		find(currentMsg.msgContent())?.destructured?.
									    			let { (x, y) -> Pair(x.toInt(), y.toInt()) }
									    server.forward("robotpos/$coordinates")
						}
						else
						 {if( checkMsgContent( Term.createTerm("coapUpdate(RESOURCE,VALUE)"), Term.createTerm("coapUpdate(RES,VAL)"), 
						                         currentMsg.msgContent()) ) { //set msgArgList
						 		 server.forward("${payloadArg(0)}/" + payloadArg(1))  
						 }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="observing", cond=doswitch() )
				}	 
			}
		}
}
