/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 var allarme: String = ""  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | init e engage basicrobot")
						request("engage", "engage(transporttrolley,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="engaged",cond=whenReply("engagedone"))
					transition(edgeName="t017",targetState="quit",cond=whenReply("engagerefused"))
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | basicrobot engaged")
						updateResourceRep( "$name(OFF)" 
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						 allarme = "inHome"  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="moveToIndoor",cond=whenDispatch("gotoindoor"))
					transition(edgeName="t019",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("moveToIndoor") { //this:State
					action { //it:State
						 allarme = "toIndoor"  
						updateResourceRep( "$name(BLINK)" 
						)
						CommUtils.outmagenta("$name | vado all'INDOOR")
						request("moverobot", "moverobot(0,4)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t020",targetState="loadTheCharge",cond=whenReply("moverobotdone"))
					transition(edgeName="t021",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("loadTheCharge") { //this:State
					action { //it:State
						 allarme = "inIndoor"  
						updateResourceRep( "$name(ON)" 
						)
						CommUtils.outmagenta("$name | sono in INDOOR")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_loadTheCharge", 
				 	 					  scope, context!!, "local_tout_transporttrolley_loadTheCharge", 3000.toLong() )
					}	 	 
					 transition(edgeName="t22",targetState="moveToColdroom",cond=whenTimeout("local_tout_transporttrolley_loadTheCharge"))   
					transition(edgeName="t23",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("moveToColdroom") { //this:State
					action { //it:State
						 allarme = "toColdroom"  
						forward("chargetaken", "chargetaken(_)" ,"coldstorageservice" ) 
						CommUtils.outmagenta("$name | vado verso la cold room")
						updateResourceRep( "$name(BLINK)" 
						)
						request("moverobot", "moverobot(4,3)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="storeTheCharge",cond=whenReply("moverobotdone"))
					transition(edgeName="t025",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("storeTheCharge") { //this:State
					action { //it:State
						 allarme = "inColdroom"  
						updateResourceRep( "$name(ON)" 
						)
						CommUtils.outmagenta("$name | sono in Cold Room")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_storeTheCharge", 
				 	 					  scope, context!!, "local_tout_transporttrolley_storeTheCharge", 3000.toLong() )
					}	 	 
					 transition(edgeName="t026",targetState="askService",cond=whenTimeout("local_tout_transporttrolley_storeTheCharge"))   
					transition(edgeName="t027",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("askService") { //this:State
					action { //it:State
						request("chargedeposited", "chargedeposited(_)" ,"coldstorageservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t028",targetState="moveToIndoor",cond=whenReply("more"))
					transition(edgeName="t029",targetState="moveToHome",cond=whenReply("gohome"))
				}	 
				state("moveToHome") { //this:State
					action { //it:State
						 allarme = "toHome"  
						updateResourceRep( "$name(BLINK)" 
						)
						CommUtils.outmagenta("$name | vado alla posizione HOME")
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t030",targetState="trolleyathome",cond=whenReply("moverobotdone"))
					transition(edgeName="t031",targetState="sonarobstacle",cond=whenEvent("alarm"))
				}	 
				state("trolleyathome") { //this:State
					action { //it:State
						updateResourceRep( "$name(OFF)" 
						)
						CommUtils.outmagenta("$name | trolley at HOME")
						forward("setdirection", "dir(down)" ,"basicrobot" ) 
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("sonarobstacle") { //this:State
					action { //it:State
						discardMessages = true
						updateResourceRep( "$name(ON)" 
						)
						CommUtils.outmagenta("$name | Sono fermo per ostacolo sonar")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t032",targetState="idle",cond=whenEventGuarded("resume",{ allarme == "inHome"  
					}))
					transition(edgeName="t033",targetState="moveToIndoor",cond=whenEventGuarded("resume",{ allarme == "toIndoor"  
					}))
					transition(edgeName="t034",targetState="moveToColdroom",cond=whenEventGuarded("resume",{ allarme == "inIndoor"  
					}))
					transition(edgeName="t035",targetState="loadTheCharge",cond=whenEventGuarded("resume",{ allarme == "toColdroom"  
					}))
					transition(edgeName="t036",targetState="storeTheCharge",cond=whenEventGuarded("resume",{ allarme == "inColdroom"  
					}))
					transition(edgeName="t037",targetState="moveToHome",cond=whenEventGuarded("resume",{ allarme == "toHome"  
					}))
				}	 
				state("quit") { //this:State
					action { //it:State
						updateResourceRep( "$name(OFF)" 
						)
						forward("disengage", "disengage(transporttrolley)" ,"basicrobot" ) 
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
}
